version: "3.4"

services:
  artio_redis:
    image: redis
    command: redis-server --port 6380 --appendonly yes --requirepass ${REDIS_PASSWORD}
    volumes:
      - ../Data:/data
    ports:
      - 6380:6380
    restart: always
    container_name: artio_redis

  artio_backend:
    image: vlad0297/artio_backend:release
    depends_on:
      - artio_redis
    ports:
      - 42069:42069
    environment:
      REDIS_URL: artio_redis:6380
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    restart: always
    container_name: artio_backend

  artio_frontend:
    image: vlad0297/artio_frontend:release
    depends_on:
      - artio_redis
      - artio_backend
    ports:
      - 4200:4200
    restart: always
    container_name: artio_frontend
