name: Main - Testing

on:
  push:
    branches:
      - 'main'

jobs:

  artifact:

    name: Test main branch
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: Hello Test
        run: echo "Hello World!"