name: Release - Test, Build & Redeploy

on:
  push:
    branches:
      - 'release'

jobs:
  docker_backend:
    name: Publish backend to Docker Hub
    runs-on: ubuntu-18.04
    env:
      REPO: ${{ secrets.DOCKER_BACKEND_REPO }}
    defaults:
      run:
        working-directory: artio-go

    steps:
      - uses: actions/checkout@v2
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USER }} 
             -p ${{ secrets.DOCKER_PASS }}
      - name: Build Docker image
        run: docker build -t $REPO:release -t $REPO:${GITHUB_SHA::8} .
      - name: Publish Docker image
        run: docker push $REPO


  docker_frontend:
    name: Publish frontend to Docker Hub
    runs-on: ubuntu-18.04
    env:
      REPO: ${{ secrets.DOCKER_FRONTEND_REPO }}
    defaults:
      run:
        working-directory: artio-ng

    steps:
      - uses: actions/checkout@v2
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USER }} 
             -p ${{ secrets.DOCKER_PASS }}
      - name: Build Docker image
        run: docker build -t $REPO:release -t $REPO:${GITHUB_SHA::8} .
      - name: Publish Docker image
        run: docker push $REPO


  redeploy:
    name: Redeploy webhook call
    runs-on: ubuntu-18.04
    needs: [docker_backend, docker_frontend]
    steps:
      - name: Deploy docker container webhook
        uses: distributhor/workflow-webhook@v1
        env:
          webhook_url: ${{ secrets.WEBHOOK_URL }}
          webhook_secret: ${{ secrets.WEBHOOK_SECRET }}
          data: '{ "redis_password":  "${{ secrets.REDIS_PASSWORD }}" }'